name = "nwflash-web"
main = "src/index.ts"
compatibility_date = "2026-08-13"

# 让 worker 能把 admin.html 当作纯文本导入
rules = [
  { type = "Text", globs = ["**/*.html"], fallthrough = true }
]

[[d1_databases]]
binding = "DB"
database_name = "nwflash-db"
database_id = "a35d1ea1-620f-436c-9eb5-7f58312c1cf6"

# 自定义域:web.nwflash.cc.cd(域名 nwflash.cc.cd 需已在 Cloudflare)
[[routes]]
pattern = "web.nwflash.cc.cd"
custom_domain = true
