<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VivoKsu.App\VivoKsu.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\VivoKsu.App\apk\KSU.APK" Link="apk\KSU.APK" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\VivoKsu.App\apk\KernelSU.apk" Link="apk\KernelSU.apk" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\VivoKsu.App\root-tools\**\*" Link="root-tools\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\VivoKsu.App\payload-tools\payload_dumper.exe" Link="payload-tools\payload_dumper.exe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
